name: deploy.yaml
on:
  push:
    branches: [main]
    tags: ["*"]
  workflow_dispatch:

permissions:
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: true
          target: prod
          tags: ghcr.io/${{ github.repository }}:latest
          labels: org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          secret-envs: CODECOV_TOKEN=CODECOV_TOKEN
          build-args: |
            GITHUB_SHA=${{ github.sha }}
            GITHUB_REPOSITORY=${{ github.repository }}
            GITHUB_REF_NAME=${{ github.ref_name }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
