name: execute.yml
on:
  workflow_dispatch:
  schedule:
    # Run every 12 hours at 17 minutes past the hour
    - cron: "12 0/17 * * *"

permissions: read-all

jobs:
  execute:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Render quarto site
        run: quarto render
        working-directory: /app
        env:
          NO_COLOR: 1

      - name: Create commit message
        id: commit_message_step
        run: |
          echo "commit_message=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_OUTPUT

      # This is needed to keep the cron job running. We want to keep it out of
      # the main branch to avoid cluttering the history
      - name: Publish data
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: /app/data
          branch: data
          commit-message: Bump date
          single-commit: true

      - name: Publish site
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          clean: false
          branch: gh-pages
          folder: docs
